name: algomate
description: "Professional algorithm selection companion with intelligent strategy selection, built-in benchmarking, and performance optimization."
version: 0.1.5
homepage: https://github.com/Kidpech-code/algomate
repository: https://github.com/Kidpech-code/algomate
issue_tracker: https://github.com/Kidpech-code/algomate/issues
documentation: https://github.com/Kidpech-code/algomate#readme
topics:
  - algorithms
  - sorting
  - searching
  - performance
  - optimization
funding:
  - https://github.com/sponsors/Kidpech-code

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.11.0

dev_dependencies:
  test: ^1.25.0
  benchmark_harness: ^2.2.2
  lints: ^4.0.0

# Pub.dev platform compatibility
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# Execution environments
executables:

# Additional metadata for pub.dev scoring
false_secrets:
  - example
  - test
