# AlgoMate Flutter Web Demo - Docker Compose
version: "3.8"

services:
  algomate-demo:
    build: .
    ports:
      - "8080:80"
    container_name: algomate-flutter-web-demo
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.algomate.rule=Host(`algomate-demo.localhost`)"
      - "traefik.http.services.algomate.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  # nginx-proxy:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - algomate-demo
